### ISSUE TITLE
it

### ISSUE THREAD

**Issue by XiaohuanIT** [nityanandagohain/proxy_configuration#5]
it does not work. My operating system is ubuntu14.04, which has GUI. I set the proxy in the enviroment, whose file is in ~/.bashrc, and I done your suggets operation on the computer, but it does not work. I want to get your help.

**Comment by nityanandagohain** [comment]
@XiaohuanIT 
Sorry for replying late. 
can you give a screen shot of what happened when you run this script.

**Comment by XiaohuanIT** [comment]
Thank your reply. I have get these points about the proxy agent: the first, the browser's proxy will be effective only when the authority authentication are complete at the browser setting; the second, the shell enviroment's proxy will work only when the proxy config is configured at the file such "~/.bashrc". And the shell enviroment's proxy config will not make the browser work well. The shell enviroment and browser are independent about proxy. I guess that the shell enviroment and browser take different ways on the proxy. By the way, your script's product is good.

**Comment by nityanandagohain** [comment]
Yes it is only effective in your shell and not in the browser btw thanks.
